CREATE TABLE tb_USUARIO
(
	ID_USUARIO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NOMBRE_USUARIO VARCHAR(32) NOT NULL,
	CONTRASENNA VARCHAR(32) NOT NULL,
);

CREATE TABLE tb_CLIENTE	
(
	ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	NOMBRE_CLIENTE VARCHAR(32) NOT NULL,
	APELLIDOS VARCHAR(32) NOT NULL,
	EDAD INT NOT NULL,
	TELEFONO VARCHAR(32) NOT NULL,
	EMAIL VARCHAR(32) NOT NULL,
	ENFERMEDAD VARCHAR(300) NULL,
	IS_DELETED BIT DEFAULT 0 NULL
);

CREATE TABLE tb_TIPO_PAGO
(
	ID_TIPO_PAGO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	NOMBRE_TIPO VARCHAR(32) NOT NULL
);

CREATE TABLE tb_PAGO
(
	ID_PAGO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	FECHA DATETIME NOT NULL,
	TIPO_PAGO INT NOT NULL,
	MONTO FLOAT(53) NOT NULL,
	DETALLE VARCHAR (300) NOT NULL,
	CONSTRAINT fk_id_cliente_pago FOREIGN KEY (ID_CLIENTE) REFERENCES  ADMIN.tb_CLIENTE(ID_CLIENTE),
	CONSTRAINT fk_id_tipo_pago_pago FOREIGN KEY (TIPO_PAGO) REFERENCES ADMIN.tb_TIPO_PAGO(ID_TIPO_PAGO)
);

CREATE TABLE tb_DATOS_CLIENTE
(
	ID_DATOS INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	PESO VARCHAR(32) NULL,
	ALTURA VARCHAR(32) NULL,
	GRASA_CORPORAL VARCHAR(32)NULL,
	AGUA_CORPORAL VARCHAR(32) NULL,
	MASA_MUSCULAR VARCHAR(32) NULL,
	VALORACION_FISICA VARCHAR(32) NULL,
	METABOLISMO_BASAL VARCHAR(32)NULL,
	EDAD_METABOLICA VARCHAR(32) NULL,
	MASA_OSEA VARCHAR(32)NULL,
	GRASA_VISCERAL VARCHAR(32)NULL
);

CREATE TABLE tb_CIRCUNFERENCIA_CLIENTE
(
	ID_CIRCUNFERENCIA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	BRAZO_DERECHO VARCHAR(32)NULL,
	BRAZO_IZQUIERDO VARCHAR(32) NULL,
	PECHO VARCHAR(32) NULL,
	ABDOMEN VARCHAR(32) NULL,
	CADERA VARCHAR(32) NULL,
	MUSLO_DERECHO VARCHAR(32) NULL,
	MUSLO_IZQUIERDO VARCHAR(32) NULL,
	PIERNA_DERECHO VARCHAR(32) NULL,
	PIERNA_IZQUIERDA VARCHAR(32) NULL
);

CREATE TABLE tb_MEDICION_CLIENTE
(
	ID_MEDICION INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	ID_DATOS INT NOT NULL,
	ID_CIRCUNFERENCIA INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	FECHA DATETIME NOT NULL, 
	CONSTRAINT fk_id_medicion_cliente FOREIGN KEY (ID_CLIENTE) REFERENCES  ADMIN.tb_CLIENTE(ID_CLIENTE),
	CONSTRAINT fk_id_medicion_datos FOREIGN KEY (ID_DATOS) REFERENCES  ADMIN.tb_DATOS_CLIENTE(ID_DATOS),
 	CONSTRAINT fk_id_medicion_circunferencia FOREIGN KEY (ID_CIRCUNFERENCIA ) REFERENCES   ADMIN.tb_CIRCUNFERENCIA_CLIENTE(ID_CIRCUNFERENCIA )
);

CREATE TABLE tb_RUTINA
(
	ID_RUTINA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	FECHA DATETIME NOT NULL,
	NIVEL VARCHAR(32) NOT NULL,
	TIPO VARCHAR(32) NOT NULL,
	OBJETIVO VARCHAR(32) NOT NULL,
	PORCENTAJE VARCHAR(32) NULL,
	PAUSA VARCHAR(32) NOT NULL
);

CREATE TABLE ADMIN.tb_EJERCICIO
(
	ID_EJERCICIO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	NOMBRE_EJERCICIO VARCHAR(100) NOT NULL
);

CREATE TABLE tb_RUTINA_EJERCICIO
(
	ID_RUTINA INT  AUTO_INCREMENT NOT NULL,
	ID_EJERCICIO INT NOT NULL,
	INDICACIONES VARCHAR(300) NULL,
	CONSTRAINT pk_rutina_ejercicio PRIMARY KEY (ID_RUTINA,ID_EJERCICIO),
	CONSTRAINT fk_id_rutina FOREIGN KEY (ID_RUTINA) REFERENCES tb_RUTINA(ID_RUTINA),
	CONSTRAINT fk_id_ejercicio FOREIGN KEY (ID_EJERCICIO) REFERENCES tb_EJERCICIO(ID_EJERCICIO)
);

CREATE TABLE tb_GRUPO_MUSCULAR
(
	ID_MUSCULAR INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	NOMBRE_GRUPO_MUSCULAR VARCHAR(100) NOT NULL
);

CREATE TABLE tb_EJERCICIO_GRUPO
(
	ID_EJERCICIO INT NOT NULL,
	ID_GRUPO INT NOT NULL,
	CONSTRAINT pk_ejercicio_grupo PRIMARY KEY (ID_EJERCICIO, ID_GRUPO),
	CONSTRAINT fk_id_ejercicio_grupo FOREIGN KEY (ID_EJERCICIO) REFERENCES tb_EJERCICIO (ID_EJERCICIO),
	CONSTRAINT fk_id_grupo_ejercicio FOREIGN KEY (ID_GRUPO) REFERENCES tb_GRUPO_MUSCULAR(ID_MUSCULAR)
);
